<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="X.PagedList" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolAccount.Kernel\SchoolAccount.Kernel.csproj" />
    <ProjectReference Include="..\SchoolAccount.Application\SchoolAccount.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>SchoolAccount.IntegrationTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
