<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\integration\SchoolAccount.Integration.AcademiesApi\SchoolAccount.Integration.AcademiesApi.csproj" />
    <ProjectReference Include="..\SchoolAccount.Domain\SchoolAccount.Domain.csproj" />
    <ProjectReference Include="..\SchoolAccount.Kernel\SchoolAccount.Kernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="X.PagedList" />
  </ItemGroup>
</Project>
