<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\SchoolAccount.Domain\SchoolAccount.Domain.csproj" />
    <ProjectReference Include="..\SchoolAccount.Kernel\SchoolAccount.Kernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="contentful.aspnetcore" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Abstractions\Data\" />
  </ItemGroup>
</Project>
