GET http://localhost:5231/team/1
###
GET http://localhost:5231/team/2
###
GET http://localhost:5231/team/3
###
GET https://localhost:7299/team/4
###
GET http://localhost:5231/team/5
###
POST https://localhost:7299/team
Content-Type: application/json

{
  "name": "New Team",
  "description": "This is a newly created team.",
  "emailAddress": "test@dfe.gov.uk",
  "acronym": "NT"
}