<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>4e50a46d-becc-4223-ac73-f9f5704af747</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SchoolAccount.Application\SchoolAccount.Application.csproj" />
    <ProjectReference Include="..\SchoolAccount.Infrastructure\SchoolAccount.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" />
    <PackageReference Include="Microsoft.FeatureManagement" />
  </ItemGroup>
</Project>
