worker_processes auto;
pid /tmp/nginx.pid; # Required for unprivileged

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Unprivileged Nginx needs these temp paths set to writable locations
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    access_log off;
    error_log  /dev/stderr warn;

    sendfile        on;
    keepalive_timeout  65;

    # --- HTTP to HTTPS Redirect ---
    server {
      listen          8080;
      server_name     localhost;
      
      # Redirects to the host's HTTPS port
      return          307 https://$host:4200$request_uri;
    }

    # --- Main SSL Server ---
    server {
        listen       8443 ssl;
        server_name  localhost;
        
        # Matches your Volume Mount path in compose.yml
        ssl_certificate     /https/frontend.crt;
        ssl_certificate_key /https/frontend.key;
        
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        
        root /usr/share/nginx/html;
        index index.html;

        # Angular Routing
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Caching for assets
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|map)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}