name: Pull Request Health Checks

on:
  pull_request:
    branches: [main]
    
permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/_test.yml
    with:
      dotnet-version: '10.0.x'